[unix_http_server]
file=/tmp/supervisor.sock

[supervisord]
logfile=/tmp/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/tmp/supervisord.pid
nodaemon=true
user=frappe

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:backend]
command=/home/frappe/frappe-bench/env/bin/gunicorn --chdir=/home/frappe/frappe-bench/sites --bind=0.0.0.0:8000 --threads=4 --workers=2 --worker-class=gthread --worker-tmp-dir=/dev/shm --timeout=120 --preload frappe.app:application
directory=/home/frappe/frappe-bench
user=frappe
autostart=true
autorestart=true
stdout_logfile=/home/frappe/frappe-bench/logs/backend.log
stderr_logfile=/home/frappe/frappe-bench/logs/backend.error.log
environment=HOME="/home/frappe",USER="frappe"

[program:frontend]
command=nginx-entrypoint.sh
directory=/home/frappe/frappe-bench
user=frappe
autostart=true
autorestart=true
stdout_logfile=/home/frappe/frappe-bench/logs/frontend.log
stderr_logfile=/home/frappe/frappe-bench/logs/frontend.error.log
environment=HOME="/home/frappe",USER="frappe",BACKEND="localhost:8000",SOCKETIO="localhost:9000"

[program:websocket]
command=node /home/frappe/frappe-bench/apps/frappe/socketio.js
directory=/home/frappe/frappe-bench
user=frappe
autostart=true
autorestart=true
stdout_logfile=/home/frappe/frappe-bench/logs/websocket.log
stderr_logfile=/home/frappe/frappe-bench/logs/websocket.error.log
environment=HOME="/home/frappe",USER="frappe"

[program:scheduler]
command=bench schedule
directory=/home/frappe/frappe-bench
user=frappe
autostart=true
autorestart=true
stdout_logfile=/home/frappe/frappe-bench/logs/scheduler.log
stderr_logfile=/home/frappe/frappe-bench/logs/scheduler.error.log
environment=HOME="/home/frappe",USER="frappe"

[program:worker-long]
command=bench worker --queue long,default,short
directory=/home/frappe/frappe-bench
user=frappe
autostart=true
autorestart=true
stdout_logfile=/home/frappe/frappe-bench/logs/worker-long.log
stderr_logfile=/home/frappe/frappe-bench/logs/worker-long.error.log
environment=HOME="/home/frappe",USER="frappe"

[program:worker-short]
command=bench worker --queue short,default
directory=/home/frappe/frappe-bench
user=frappe
autostart=true
autorestart=true
stdout_logfile=/home/frappe/frappe-bench/logs/worker-short.log
stderr_logfile=/home/frappe/frappe-bench/logs/worker-short.error.log
environment=HOME="/home/frappe",USER="frappe"
